import React from 'react';
import './global.css';
import Link from 'next/link';
import { LoginButton } from '@/components/LoginButton';
import { getServerSession, Session } from 'next-auth';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import { LogoutButton } from '@/components/LogoutButton';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const session: Session | null = await getServerSession(authOptions);

  return (
    <html lang='en'>
    <body>
    <div className='navbar'>
      <Link href='/' className='logo'>Chocommunity</Link>
      <Link href={'/posts'}>Posts</Link>
      {session == null ?
        <LoginButton /> :
        <LogoutButton />
      }
    </div>
    {children}
    </body>
    </html>
  );
};
export default RootLayout;
