import React from 'react';
import './global.css';
import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang='en'>
    <body>
    <div className='navbar'>
      <Link href='/' className='logo'>Chocommunity</Link>
      <Link href='/posts'>Posts</Link>
    </div>
    {children}
    </body>
    </html>
  );
}
